require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  Exclude:
    - '**/*_pb.rb'
    - 'vendor/**/*'

  TargetRubyVersion: 2.7

  NewCops: enable

Metrics:
  Enabled: false
