require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - '**/*_pb.rb'
    - 'vendor/**/*'

  TargetRubyVersion: 3.1

  NewCops: enable

Metrics:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
