name: build

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
        bundler-cache: true

    - name: Lint
      run: bundle exec rake rubocop

  spec:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        ruby-version: ['2.6', '3.0', 'ruby', 'jruby']

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Compile
      run: bundle exec rake compile

    - name: Spec
      run: bundle exec rake spec

  release:

    needs: [lint, spec]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby

    - name: Release
      run: rake -f -r bundler/gem_tasks release gem_push=no
