name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        ruby-version: ['2.6', '2.7', '3.0']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Test
      run: bundle exec rake

    - name: Install Gem
      run: rake install

    - name: Test Gem
      run: |-
        ruby -r sass -e "puts Sass.render(data: 'h1 { color: black; }').css"
